/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRoutingRouteImport } from './routes/_authenticated/routing'
import { Route as AuthenticatedRoadsRouteImport } from './routes/_authenticated/roads'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedFutureRouteImport } from './routes/_authenticated/future'
import { Route as AuthenticatedComplaintsRouteImport } from './routes/_authenticated/complaints'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutingRoute = AuthenticatedRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoadsRoute = AuthenticatedRoadsRouteImport.update({
  id: '/roads',
  path: '/roads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFutureRoute = AuthenticatedFutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComplaintsRoute = AuthenticatedComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/future': typeof AuthenticatedFutureRoute
  '/map': typeof AuthenticatedMapRoute
  '/roads': typeof AuthenticatedRoadsRoute
  '/routing': typeof AuthenticatedRoutingRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/future': typeof AuthenticatedFutureRoute
  '/map': typeof AuthenticatedMapRoute
  '/roads': typeof AuthenticatedRoadsRoute
  '/routing': typeof AuthenticatedRoutingRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/complaints': typeof AuthenticatedComplaintsRoute
  '/_authenticated/future': typeof AuthenticatedFutureRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/roads': typeof AuthenticatedRoadsRoute
  '/_authenticated/routing': typeof AuthenticatedRoutingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/complaints'
    | '/future'
    | '/map'
    | '/roads'
    | '/routing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/complaints'
    | '/future'
    | '/map'
    | '/roads'
    | '/routing'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/analytics'
    | '/_authenticated/complaints'
    | '/_authenticated/future'
    | '/_authenticated/map'
    | '/_authenticated/roads'
    | '/_authenticated/routing'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routing': {
      id: '/_authenticated/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof AuthenticatedRoutingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roads': {
      id: '/_authenticated/roads'
      path: '/roads'
      fullPath: '/roads'
      preLoaderRoute: typeof AuthenticatedRoadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/future': {
      id: '/_authenticated/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof AuthenticatedFutureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/complaints': {
      id: '/_authenticated/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AuthenticatedComplaintsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedComplaintsRoute: typeof AuthenticatedComplaintsRoute
  AuthenticatedFutureRoute: typeof AuthenticatedFutureRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedRoadsRoute: typeof AuthenticatedRoadsRoute
  AuthenticatedRoutingRoute: typeof AuthenticatedRoutingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedComplaintsRoute: AuthenticatedComplaintsRoute,
  AuthenticatedFutureRoute: AuthenticatedFutureRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedRoadsRoute: AuthenticatedRoadsRoute,
  AuthenticatedRoutingRoute: AuthenticatedRoutingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
